name = "DataSort0"
uuid = "1728ee9c-15fa-4db7-9b75-8980fb16bceb"
license = "MIT"
authors = ["Abel Ho <your@email.com>"]
description = "A Julia package for data repository management: traversing directories, tabulating, summarizing, and updating data collections."
version = "0.0.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VideoIO = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.0"
FFMPEG = "0.4.4"
FileIO = "1.17.0"
JSON = "1.0.1"
Test = "1.11.0"
VideoIO = "1.3.0"
